[package]
name = "test_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solitaire = {path = ".."}
regex = "1.10.2"
lazy_static = "1.4.0"